### PR TITLE
Enhancement: Use jgt_tools

### PR DESCRIPTION
**Pull request by brolewis**
Migrate from maintained scripts to JGT Tools.

### CODE REVIEW

**Review by bradsbrown — APPROVED** [review]

**Review by dgou — COMMENTED** [review]
I think this PR will be obsolete when the jgt_tools PR #30 lands?

**Comment by brolewis** [comment]
@dgou Why do you think these PRs will be obsolete when jgt_tools#30 lands? These repositories are not currently using jgt_tools in any way and these PRs are to move over to use this tool instead of a series of one-off, internally-maintained scripts.

**Comment by dgou** [comment]
> @dgou Why do you think these PRs will be obsolete when jgt_tools#30 lands? These repositories are not currently using jgt_tools in any way and these PRs are to move over to use this tool instead of a series of one-off, internally-maintained scripts.

Because this adapts for `jgt_tools` 0.2... and PR #30 will bump that to 0.3.0
So this PR will work, but if we're going to go to `jgt_tools` why not go to 0.3.0 since that is probably going to land really soon. If 0.3.0 was a massive change, I could see moving to 0.2.x but it just feels like it'd be simpler to go straight to 0.3

**Comment by dgou** [comment]
Created a few venv, pulled this PR, ran bootstrap :heavy_check_mark: , ran self check :heavy_check_mark: , but run-tests:
```
============================================================== FAILURES ===============================================================
___________________________________________________________ test_munchifier ___________________________________________________________

sample_configs = '/tmp/pytest-of-dgou/pytest-0/qe_config_tests0/cake.config'

    def test_munchifier(sample_configs):
        """Test conversion from config parser to munch."""
        # Munch has it's own tests, we're just spot checking our conversion function.
>       config_by_dots = munchify_config(load_cake(sample_configs, "L1"))

tests/test_config.py:187: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

config_parser = <configparser.ConfigParser object at 0x7f1f74b809a0>

    def munchify_config(config_parser):
        """
        Create a ``munch`` version of the config_parser's data.
    
        ``munch`` allows both attribute and item access to it's data.
        See the `munch`_ documentation for details.
    
        Note: This is a one-time conversion,
        if the ``config_parser`` is subsequently updated,
        the returned ``munch`` will be unaffected.
        """
>       from munch import Munch
E       ModuleNotFoundError: No module named 'munch'

layered_config/__init__.py:255: ModuleNotFoundError
================================================= 1 failed, 19 passed in 0.08 seconds =================================================
```

**Review by dgou — APPROVED** [review]
Finally got a chance to repull this PR (as of the 5th commit) and all the scripts are working.
LGTM.

**Pull request merged**
